// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_led_switch = lv_switch_create(ui_Index);
    lv_obj_set_width(ui_led_switch, 94);
    lv_obj_set_height(ui_led_switch, 50);
    lv_obj_set_x(ui_led_switch, 44);
    lv_obj_set_y(ui_led_switch, 106);
    lv_obj_set_align(ui_led_switch, LV_ALIGN_CENTER);


    ui_led_switch_label = lv_label_create(ui_Index);
    lv_obj_set_width(ui_led_switch_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_led_switch_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_led_switch_label, 40);
    lv_obj_set_y(ui_led_switch_label, 61);
    lv_obj_set_align(ui_led_switch_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_led_switch_label, "LED Y");
    lv_obj_set_style_text_color(ui_led_switch_label, lv_color_hex(0xFF9600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_led_switch_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_led_switch_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Index);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, 139);
    lv_obj_set_y(ui_Arc1, -67);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);


    ui_Button1 = lv_btn_create(ui_Index);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 169);
    lv_obj_set_y(ui_Button1, 107);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    ui_Roller1 = lv_roller_create(ui_Index);
    lv_roller_set_options(ui_Roller1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 160);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, -169);
    lv_obj_set_y(ui_Roller1, -61);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);

    ui_Slider1 = lv_slider_create(ui_Index);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 170);
    lv_obj_set_height(ui_Slider1, 16);
    lv_obj_set_x(ui_Slider1, -121);
    lv_obj_set_y(ui_Slider1, 61);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Checkbox1 = lv_checkbox_create(ui_Index);
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -43);
    lv_obj_set_y(ui_Checkbox1, -80);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox2 = lv_checkbox_create(ui_Index);
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, -37);
    lv_obj_set_y(ui_Checkbox2, -17);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox3 = lv_checkbox_create(ui_Index);
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox3, -42);
    lv_obj_set_y(ui_Checkbox3, -51);
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


}
